services:
  app1:
    build: .
    expose:
      - "3000"
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  app2:
    build: .
    expose:
      - "3000"
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge