services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production 