global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'virtual-browser'
    static_configs:
      - targets: ['app1:3000', 'app2:3000']
    metrics_path: '/metrics' 